### ISSUE TITLE
Retrieve authorization state via whoami

### ISSUE THREAD

**Issue by coatless** [rstudio/rscloud#12]
It would be great to see the login credentials active in the _R_ session's `.global` environment, c.f. 

https://github.com/rstudio/rscloud/blob/85b286847dbe30db19b09a4dde5dd38b1aa4b6f3/R/setup.R#L3

Something like:

```
rscloud_whoami()
# User: user@example.edu
# CLIENT_ID: 981....AFG
# CLIENT_SECRET: 11Z...GGA
# Hourly API Calls: 1/100
```

**Comment by tareefk** [comment]
What is the use case here?  Are you thinking you are going to be connecting via different credentials?

**Comment by coatless** [comment]
More of a sanity check to verify user-specific setup and if rate limits come into play with the API a quick diagnostic tool.

**Comment by tareefk** [comment]
Got it, thanks.
