### ISSUE TITLE
API reference document from host team?

### ISSUE THREAD

**Issue by coatless** [rstudio/rscloud#20]
Who is the "host team"? And is it possible to get the API reference docs? 

https://github.com/rstudio/rscloud/blob/85b286847dbe30db19b09a4dde5dd38b1aa4b6f3/R/spaces.R#L112-L117

**Comment by mine-cetinkaya-rundel** [comment]
Goal is to provide better documentation for specific functions so users can tell what API calls they can make, therefore I'll close this issue since we won't be making the full documentation public yet.
