### ISSUE TITLE
rstudio.cloud memory space limit issue

### ISSUE THREAD

**Issue by englianhu** [rstudio/rscloud#42]
https://github.com/sparklyr/sparklyr/issues/2769#issuecomment-720626003

There will be easier to use RStudio.Cloud but i faced memory space issue.
https://community.rstudio.com/t/unable-save-new-file-import-github-repo/85848/5?u=englianhu

**Comment by mine-cetinkaya-rundel** [comment]
I believe this has been addressed in https://community.rstudio.com/t/unable-save-new-file-import-github-repo/85848/6 so closing here.
