### ISSUE TITLE
space_member_remove, only removing one user at a time

### ISSUE THREAD

**Issue by Ghotitox** [rstudio/rscloud#51]
I am feeding a data frame to the command, it removes one at a time and then gives message/error:

```r
Using `user_id` column.
Error in ui_field("user_id") : could not find function "ui_field"
```
Workflow:

```r
my.list <- rscloud_space_list() #I confirm that this is correct, then
f21.001.s <- space_member_list(my.list[2,1]) #select one space, create member list data frame
f21.001.rm <- f21.001.s[-3,] #remove myself from the list, I am 3rd in the list
space_member_remove(my.list[2,1],f21.001.rm, remove_projects = TRUE, ask = FALSE)
```

Returns the error given above. It deletes only the first user in the list.

**Comment by mine-cetinkaya-rundel** [comment]
I'm not able to replicate the error. Could you reinstall the package and try again? The `ui_field()` function is used in constructing the messages that are printed. Somehow it seems like you might have ended up in a state where the usethis package isn't installed for you. rscloud should be importing usethis upon installation.

**Comment by Ghotitox** [comment]
> Could you reinstall the package and try again? The `ui_field()` function is used in constructing the messages that are printed. 

I reinstalled, and it seems to be working now.  Thanks!

**Comment by mine-cetinkaya-rundel** [comment]
Great, thanks for the update!
