### ISSUE TITLE
Adjust space membership functions.

### ISSUE THREAD

**Issue by ssinnott** [rstudio/rscloud#53]
We're adjust the project cleanup options around adding and removing users from a space. We need to adjust this function here as well to support the newer options,

https://github.com/rstudio/rscloud/blob/master/R/members.R#L166

**Comment by mine-cetinkaya-rundel** [comment]
Sounds good. Do you want to do a PR or want to provide a bit more specifics and I can?

**Comment by ssinnott** [comment]
I'll do a PR for it - this is part of active work. The endpoint doesn't exist yet - so I'll add more details once the API is set in stone =)
